name: flutter_gcs_manager
description: "Flutter package that provides seamless interaction with Google Cloud Storage (GCS)."
version: 0.1.0
homepage: https://github.com/leadingtechnology/flutter_gcs_manager
repository: https://github.com/leadingtechnology/flutter_gcs_manager.git
issue_tracker: https://github.com/leadingtechnology/flutter_gcs_manager/issues

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  dio: ^5.7.0
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0

  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
